### ISSUE TITLE
CMC práctica dos, economización del código.

### ISSUE THREAD

**Issue by Duxy1996** [kauron/etsinf3#1]
Se puede hacer mas sencillo utilizando los métodos IntegerDigits, que te saca los 8 primeros números en binario y el número de la regla en binario. Con esto luego los juntas y te queda mas sencillito. @josepdd y yo lo hemos revisado.

**Comment by zhonskate** [comment]
PR welcome

**Comment by jiwidi** [comment]
donde esta esa PR duran?

**Comment by Duxy1996** [comment]
integerDigits[n,2,8], siendo n el número que quieres convertir, 2 la base binaria y 8 el número en cuestión de elementos que quieres que tenga el array de salida.

**Comment by Duxy1996** [comment]
Dejo el enlace de como funciona: https://reference.wolfram.com/language/ref/IntegerDigits.html.en

**Comment by jiwidi** [comment]
Darte manita arriba a tu propio mensaje en el op es un poco triste

**Comment by jiwidi** [comment]
ahora quita la manita si

**Comment by Duxy1996** [comment]
Es bueno fomentar una discusión constructiva. Hablar de cosas externas como si se tratase de una red social cualquiera, quizá no es lo adecuado en GitHub.

**Comment by jiwidi** [comment]
mindungui

**Comment by Duxy1996** [comment]
mindundi*
